### PR TITLE
fix duckdns token reset bug

### LINKED ISSUE #240: Cannot switch to duckdns certificate after restarting container using other validation method
[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]
	

At some point after the duckdns validation was released, I pulled and restarted my container that was configured to use http validation.  Today, I updated my docker-compose configuration to use duckdns validation, but, the post to duckdns to update the TXT record failed.  The logs suggested that my `DUCKDNSTOKEN` was incorrect.

I was sure I was doing something wrong, so, I dug through the code.  What I eventually realized was that my `donoteditthisfile.conf` had `DUCKDNSTOKEN` set to `""` (because the last time that file was updated I was using HTTP validation).  Even though `DUCKDNSTOKEN` was correctly set in my environment, when `duckdns-txt` sourced `donoteditthisfile.conf`, it was clearing the token, and as a result, I couldn't update my TXT record.

I worked around by deleting that variable from `donoteeditthisfile.conf`.  After doing that, I was able to successfully validate.  Although this workaround works, this still seems like a bug.  I *think* the solution may be as simple as not sourcing `donoteditthisconfig.conf` in `duckdns-txt`, but, I feel like it must be in there for some reason that I'm not seeing.

### PR DESCRIPTION
**Pull request by aptalca**
[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]
	

##  Thanks, team linuxserver.io

closes #240

### CODE REVIEW

File: root/etc/cont-init.d/50-config [hunk 1]
```diff
@@ -208,7 +208,7 @@ if [ ! "$URL" = "$ORIGURL" ] || [ ! "$SUBDOMAINS" = "$ORIGSUBDOMAINS" ] || [ ! "
 fi
```
Comment (pumbaasdad) [inline root/etc/cont-init.d/50-config]: Should `DUCKDNSTOKEN` also be printed out up on line 16?

When I ran into this issue last night, I assumed it wasn't there for security reasons, but, we're already writing the token to the file, so, that makes me think its probably not a security thing.  Might make debugging a problem easier for someone in the future.

Comment (aptalca) [reply root/etc/cont-init.d/50-config]: That part at the top is just so that there are some default values to compare to when trying to decide whether certs should be recreated. DUCKDNSTOKEN is not checked to see whether it changed so it's not needed to set it there.
